BEGIN;

DROP TABLE IF EXISTS RESERVATION CASCADE;

CREATE TABLE RESERVATION (
  RESERVE_NO VARCHAR(10) NOT NULL,
  RESERVE_DATE DATE NOT NULL,
  TOTAL_FARE INT NOT NULL,
  REP_CUSTOMER_NO VARCHAR(10) NOT NULL,
  REP_NAME VARCHAR(60) NOT NULL,
  REP_FURI_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT PK_RESERVATION PRIMARY KEY (RESERVE_NO);

COMMIT;