BEGIN;

INSERT INTO ACCOUNT (USER_ID, PASSWORD, FIRST_NAME, LAST_NAME, PREMIUM) VALUES ('0000000001', '$2a$10$Qw2MNZOa5tHZUhp5clz.5esaVy4NQioc2xvXBYyUcwBPhha.hxgOu', 'Hanako', 'Denden', true);
INSERT INTO ACCOUNT (USER_ID, PASSWORD, FIRST_NAME, LAST_NAME, PREMIUM) VALUES ('0000000002', '$2a$10$Qw2MNZOa5tHZUhp5clz.5esaVy4NQioc2xvXBYyUcwBPhha.hxgOu', 'Taro', 'Denden', false);

COMMIT;