# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: prdi

cloud:
  aws:
    stack:
      auto: false

functionaltest:
    download:
      expiration: 30
      roleName: s3-direct-download
      roleSessionName: s3-direct-download01
