BEGIN;

DROP TABLE IF EXISTS MESSAGE_ID_STORE CASCADE;

CREATE TABLE MESSAGE_ID_STORE (
  MESSAGE_ID VARCHAR(100) NOT NULL
);

ALTER TABLE MESSAGE_ID_STORE ADD CONSTRAINT  PK_MESSAGE_ID PRIMARY KEY (MESSAGE_ID);

COMMIT;
