# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ssmn
  session:
    store-type: redis
    # Session Timeout setting(Junit実行時は Selenide.property の until.session.timeout.sec の値のほうが大きいことを確認すること。)
    timeoutSecond: 10
  redis:
    listener:
      concurrencyLimit: 2

cloud:
  aws:
    stack:
      auto: false

management:
  endpoints:
    web:
      base-path: /management