# 環境依存しないフレームワークの設定値

spring:
  application:
    name: prcd

cloud:
  aws:
    stack:
      auto: false
      
# CloudFront Signature
functionaltest:
  cf:
    signature:
      protocol: https
      secure: true
      domain: tera-ci.net
      cookiePath: /prcd
      distributionDomain: www.tera-ci.net
      privateKeyFilePath: ${user.home}/private-key.der
      resourcePath: prcd/paid/*
      keyPairId: APKAI5K77TUXVDZ7KYZQ
      timeToActive: 1
      timeToExpire: 2
      allowedIpRange: 0.0.0.0/0