BEGIN;

DROP TABLE IF EXISTS ACCOUNT CASCADE;

CREATE TABLE ACCOUNT (
  USER_ID VARCHAR(10) NOT NULL,
  PASSWORD  VARCHAR(60) NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (USER_ID);

DROP TABLE IF EXISTS MEMBER CASCADE;

CREATE TABLE MEMBER (
  CUSTOMER_NO VARCHAR(10) NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  FURI_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT DTSH_PK_MEMBER PRIMARY KEY (CUSTOMER_NO);

COMMIT;