# for CI environment on EC2
cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
    # 認証情報の取得抑制
    credentials:
      instanceProfile: false
    # DynamoDB
    dynamodb:
      endpoint: http://dynamodb.ap-northeast-1.amazonaws.com

# RDB(RDSを使用)
database:
  url: jdbc:postgresql://ci-functionaltest-1-1-x.XXXX.ap-northeast-1.rds.amazonaws.com:5432/functionaltest
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

# connection pool for RDB
cp:
  maxActive: 96
  maxIdle: 16
  minIdle: 16
  initialSize: 16
  maxWait: 60000
  validationQuery: SELECT 1
  testOnConnect: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 120000
  removeAbandoned: true
  removeAbandonedTimeout: 60

# Logging
logging:
  path: /var/log/applogs

# Application
app:
  uploadDir: /src/test/resources/upload
  downloadDir: /src/test/resources/download
