BEGIN;

CREATE TABLE IF NOT EXISTS ACCOUNT (
  USER_ID VARCHAR(10) NOT NULL,
  PASSWORD  VARCHAR(88) NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (USER_ID);

CREATE TABLE RDRP2_USER (
  USER_ID SERIAL NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE RDRP2_USER ADD CONSTRAINT PK_RDRP2_USER PRIMARY KEY (USER_ID);

COMMIT;