# 環境依存しないフレームワークの設定値

spring:
  application:
    name: hlch-rdb-down
  datasource:
    initialize: false

management:
  endpoints:
    web:
      base-path: /management
    # Set all actuator endpoints disabled by default
    enabled-by-default: false
  endpoint:
    health:
      # Disable sensitive filter for the health endpoint
      show-details: ALWAYS
      # Enable only health endpoint
      enabled: true

cloud:
  aws:
    stack:
      auto: false

