BEGIN;

DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  USER_ID VARCHAR(10) NOT NULL,
  PASSWORD  VARCHAR(88) NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (USER_ID);

COMMIT;