BEGIN;

DROP TABLE IF EXISTS ACCOUNT CASCADE;

CREATE TABLE ACCOUNT (
  USER_ID VARCHAR(10) NOT NULL,
  PASSWORD  VARCHAR(60) NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL,
  CONSTRAINT PK_ACCOUNT PRIMARY KEY (USER_ID)
);
 
DROP TABLE IF EXISTS TRANSACTION_TOKEN CASCADE;
DROP SEQUENCE IF EXISTS TRANSACTION_TOKEN_SEQUENCE CASCADE;

DROP INDEX IF EXISTS TRANSACTION_TOKEN_INDEX_DELETE_OLDER;
DROP INDEX IF EXISTS TRANSACTION_TOKEN_INDEX_DELETE_OLDER_SEQUENCE;
DROP INDEX IF EXISTS TRANSACTION_TOKEN_INDEX_CLEAN;
 
CREATE TABLE TRANSACTION_TOKEN (
    TOKEN_NAME VARCHAR(256) NOT NULL,
    TOKEN_KEY VARCHAR(32) NOT NULL,
    TOKEN_VALUE VARCHAR(32) NOT NULL,
    SESSION_ID  VARCHAR(256) NOT NULL,
    SEQUENCE BIGINT,
    CONSTRAINT SSMN_SENF_PK_TRANSACTION_TOKEN PRIMARY KEY (TOKEN_NAME, TOKEN_KEY, SESSION_ID)
);
 
CREATE INDEX TRANSACTION_TOKEN_INDEX_DELETE_OLDER on TRANSACTION_TOKEN(TOKEN_NAME, SESSION_ID);
CREATE INDEX TRANSACTION_TOKEN_INDEX_DELETE_OLDER_SEQUENCE on TRANSACTION_TOKEN(SEQUENCE);
CREATE INDEX TRANSACTION_TOKEN_INDEX_CLEAN on TRANSACTION_TOKEN(SESSION_ID);
 
CREATE SEQUENCE TRANSACTION_TOKEN_SEQUENCE;

/* 商品テーブル */
DROP TABLE IF EXISTS PRODUCT CASCADE;

CREATE TABLE PRODUCT(
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRICE INT NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);
 
COMMIT;