# Config Server 設定値
server:
  port: 8888

cloud.aws:
  stack.auto: false
  # 認証情報の取得抑制
  credentials:
    instanceProfile: false

# ConfigServerへのヘルスチェック-停止リクエスト許可設定
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure.include: shutdown, health
