# 環境依存しないフレームワークの設定値

spring:
  application:
    name: ssmn
  session:
    store-type: redis
    timeoutSecond: 30
  redis:
    listener:
      concurrencyLimit: 2

cloud:
  aws:
    stack:
      auto: false

server:
  session:
    timeoutSecond: 30