# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hlch-disable

management:
  endpoints:
    web:
      base-path: /management
    # Set all actuator endpoints disabled by default
    enabled-by-default: false
  endpoint:
    health:
      # Disable sensitive filter for the health endpoint
      show-details: ALWAYS
      # Enable only health endpoint
      enabled: true
  health:
    dynamodb:
      enabled: false

cloud:
  aws:
    stack:
      auto: false
 
amazon:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-1.amazonaws.com