# 環境依存しないフレームワークの設定値

spring:
  application:
    name: hlch-disable

management:
  context-path: /management
  # Disable security for actuator endpoints
  security:
    enabled: false
  health:
    dynamodb:
      enabled: false

endpoints:
  # Set all actuator endpoints disabled by default
  enabled: false
  health:
    # Disable sensitive filter for the health endpoint
    sensitive: false
    # Enable only health endpoint
    enabled: true  

cloud:
  aws:
    stack:
      auto: false
 
amazon:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-1.amazonaws.com