# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: prqu

cloud:
  aws:
    stack:
      auto: false
    # SQS
    sqs:
      region: ap-northeast-1