spring:
  profiles:
    include: high-priority-queue, low-priority-queue
# for development environment on local PC
cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
# 認証情報の取得抑制
    credentials:
      instanceProfile: false

# RDB(ローカルPC上のPostgreSQLを使用)
database:
  url: jdbc:postgresql://localhost:5432/functionaltest
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

# connection pool for RDB
cp:
  maxActive: 96
  maxIdle: 16
  minIdle: 16
  initialSize: 16
  maxWait: 60000
  validationQuery: SELECT 1
  testOnConnect: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 120000
  removeAbandoned: true
  removeAbandonedTimeout: 60

# Logging
logging:
  path: /var/log/applogs
  
app:
  priority:
    queue:
      high:
       name: FT_PRIORITY_QUEUE_HIGH
       concurrency: 10
      low:
       name: FT_PRIORITY_QUEUE_LOW
       concurrency: 5

