# for development environment on local PC
cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
# 認証情報の取得抑制
    credentials:
      instanceProfile: false
    # dynamoDB region
    dynamodb:
      region: ap-northeast-1

# RDB sharding(ローカルPC上のPostgreSQLを使用)
database:
  common:
    data-source:
      driverClassName: org.postgresql.Driver
      maxActive: 96
      maxIdle: 16
      minIdle: 0
      maxWait: 90000
      password: postgres
      username: postgres
  default:
    schema:
      name: default
  data-sources:
    - schema: default
      url: jdbc:postgresql://localhost:5432/functionaltest
    - schema: shard1
      url: jdbc:postgresql://localhost:5432/functionaltest_shard1
    - schema: shard2
      url: jdbc:postgresql://localhost:5432/functionaltest_shard2
      maxActive: 30

# Logging
logging:
  path: /var/log/applogs
