# for CI environment on EC2
    # AWS common
cloud:
  aws:
    region:
    auto: true

# RDB(RDSを使用)
database:
  url: jdbc:postgresql://ci-functionaltest.XXXX.ap-northeast-1.rds.amazonaws.com:5432/functionaltest
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

# connection pool for RDB
cp:
  maxActive: 96
  maxIdle: 16
  minIdle: 16
  initialSize: 16
  maxWait: 60000
  validationQuery: SELECT 1
  testOnConnect: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 120000
  removeAbandoned: true
  removeAbandonedTimeout: 60

# Logging
logging:
  path: /var/log/applogs

redis:
  session:
    cluster:
      node1: atrs-ci.xxxx.clustercfg.apne1.cache.amazonaws.com:6379
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1
    minIdle: 0
  cache:
    cluster:
      node1: atrs-ci-cache.xxxx.clustercfg.apne1.cache.amazonaws.com:6379
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1
    minIdle: 0
