# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: caab2
  session:
    store-type: redis
    redis:
      configure-action: NONE

cloud:
  aws:
    stack:
      auto: false